1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np
x = np.array([1, 2, 3, 5])
array1 = np.vander(x, increasing = False)
array1

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [2]:
x = np.array([1, 2, 3, 5])
N=4
array2 = np.column_stack([x**(N-1-i) for i in range(N)])
array2

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]], dtype=int32)

In [3]:
array3 = np.vander(x, N)
array3

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [4]:
array4 = np.vander(x, increasing=True)
array4

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])